import './globals.css'
import localFont from 'next/font/local'

const nanumMJ = localFont({
  src: '../public/fonts/NanumMyeongjo.otf',
  display: 'swap',
  variable: '--font-nanum-mj',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nanumMJ.variable}>{children}</body>
    </html>
  )
}
